channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.14.2
  - cloudpickle==3.0.0
  - packaging==24.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
name: mlflow-env
